- hosts: all
  become: yes
  tasks:
    - name: install packages
      become: true
      become_user: root
      apt:
        state: present
        name:
          - inxi
         - screenfetch
        - ansiweather