---
- hosts: all
  become: yes
  become_method: sudo
  become_user: root
  tasks:
   - name: Run the equivalent of "apt-get update" as a separate step
     ansible.builtin.apt:
      update_cache: yes
