---
- hosts: all
  become: true
  become_method: sudo
  become_user: root
  tasks:
  - name: Update all packages to their latest version
      ansible.builtin.apt:
        name: "*"
        state: latest
  - name: Remove dependencies that are no longer required and purge their configuration files
      ansible.builtin.apt:
        autoremove: yes
        purge: true
