---
- hosts: all
  become: yes
  become_method: sudo
  tasks:
  - name: Install packages
      apt:
        name:
        - inxi
        - screenfetch
        - ansiweather
        state: latest
        cache_valid_time: 3600
