---
- hosts: all
  become: true
  become_method: sudo
  become_user: root
  tasks:
  - name: Remove dependencies that are no longer required and purge their configuration files
    ansible.builtin.apt:
      autoremove: yes
      purge: true
