---
-  hosts: all
   become: yes
   tasks:

      - name: install figlet
        apt:
          name: figlet
          state: present

      - name: install inxi
        apt:
          name: inxi
          state: present

      - name: install screenfetch
        apt:
          name: screenfetch
          state: present

      - name: install ansiweather
        apt:
          name: ansiweather
          state: present


      - name: install public keys
        ansible.posix.authorized_key:
          user: jari
          state: present
          key: "{{ lookup('file', '/home/jari/.ssh/jari.pub') }}"

      # NOTE: Fully quoted because of the ': ' on the line. See the Gotchas in the YAML docs.
      - name: Validate the sudoers file before saving
        ansible.builtin.lineinfile:
          path: /etc/sudoers
          state: present
          regexp: '^%sudo'
          line: '%sudo ALL=(ALL) NOPASSWD: ALL'
          validate: /usr/sbin/visudo -cf %s
