- hosts: all
  become: yes
  become_user: jari
  tasks:
    - name: update and upgrade
      apt:
        update_cache: yes
        upgrade: 'yes'
        cache_valid_time: 30
    - name: reboot host(s)
      ansible.builtin.reboot:
        msg: "reboot by Ansible"
        pre_reboot_delay: 5
        post_reboot_delay: 30
        test_command: "whoami"
