---
- name: Update Linux host
  hosts: all
  become: yes
  become_method: sudo
  become_user: root
  tasks:
    - name: Get all updates
      ansible.builtin.apt:
        update_cache: true
        autoremove: true
        autoclean: true
