- hosts: all
  become: yes
  tasks:
  - name: update and upgrade
    apt:
     update_cache: yes
     upgrade: 'yes'
     cache_valid_time: 86400
      - name: Check if a reboot is needed
        register: reboot_required_file
        stat: path=/var/run/reboot-required get_md5=no
 
      - name: Reboot the box if kernel updated/installed
        reboot:
          msg: "Reboot initiated by Ansible for kernel updates"
          connect_timeout: 5
          reboot_timeout: 300
          pre_reboot_delay: 0
          post_reboot_delay: 30
          test_command: uptime
        when: reboot_required_file.stat.exists
