- hosts: all
  tasks:
 - name: Reboot host and wait for it to restart
   reboot:
     msg: "Reboot initiated by Ansible"
     connect_timeout: 10
     reboot_timeout: 300
     pre_reboot_delay: 0
     post_reboot_delay: 60
     test_command: whoami
   become: true
      

#- hosts: all
#  tasks:
#  - name: update and upgrade
#     apt: 
#     update_cache: yes
#     upgrade: yes
#  - name: Wait for APT Lock
#     shell:  while fuser /var/lib/dpkg/lock >/dev/null 2>&1; do sleep 5; done;
#  - name: Install Apt Packages
#     apt:
#      name: "{{ apt_packages }}"
#      state: present
#      force_apt_get: yes
