- hosts: all
  become: yes
  tasks:
  - name: update and upgrade
    apt:
     update_cache: yes
     upgrade: 'yes'
     cache_valid_time: 86400
  - name: Linux Reboot Demo
    hosts: ubuntu-base
    gather_facts: no
    remote_user: jari
    become: true
  tasks:
  - name: Reboot the machine (Wait for 5 min)
     reboot:
      reboot_timeout: 300
